print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/microlm/Four-O-Clock/Assets/Resources/Mannequins/bookcase.ma"`)
{		
	file -o "/Users/microlm/Four-O-Clock/Assets/Resources/Mannequins/bookcase.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/microlm/Four-O-Clock/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/microlm/Four-O-Clock/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/microlm/Four-O-Clock/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
